export const SIGNIN = 'SIGNIN'
export const SIGNOUT = 'SIGNOUT'
export const SIGNUP = 'SIGNUP'

export const GET_POSTS = 'GET_POSTS'
export const ADD_POST = 'ADD_POST'
export const GET_TAGS = 'GET_TAGS'
export const GET_USERPOSTS = 'GET_USERPOSTS'
export const DELETE_POST = 'DELETE_POST'
export const EDIT_USER = 'EDIT_USER'